---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: projectconfigs.paas.bk.tencent.com
spec:
  group: paas.bk.tencent.com
  names:
    kind: ProjectConfig
    listKind: ProjectConfigList
    plural: projectconfigs
    singular: projectconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ProjectConfig is the Schema for the project configs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          autoscaling:
            description: AutoscalingConfig contains the config for autoscaling
            properties:
              enabled:
                description: Enabled indicates whether autoscaling is enabled
                type: boolean
            required:
            - enabled
            type: object
          cacheNamespace:
            description: |-
              CacheNamespace if specified restricts the manager's cache to watch objects in
              the desired namespace Defaults to all namespaces


              Note: If a namespace is specified, controllers can still Watch for a
              cluster-scoped resource (e.g Node).  For namespaced resources the cache
              will only hold objects from the desired namespace.
            type: string
          controller:
            description: |-
              Controller contains global configuration options for controllers
              registered within this manager.
            properties:
              cacheSyncTimeout:
                description: |-
                  CacheSyncTimeout refers to the time limit set to wait for syncing caches.
                  Defaults to 2 minutes if not set.
                format: int64
                type: integer
              groupKindConcurrency:
                additionalProperties:
                  type: integer
                description: |-
                  GroupKindConcurrency is a map from a Kind to the number of concurrent reconciliation
                  allowed for that controller.


                  When a controller is registered within this manager using the builder utilities,
                  users have to specify the type the controller reconciles in the For(...) call.
                  If the object's kind passed matches one of the keys in this map, the concurrency
                  for that controller is set to the number specified.


                  The key is expected to be consistent in form with GroupKind.String(),
                  e.g. ReplicaSet in apps group (regardless of version) would be `ReplicaSet.apps`.
                type: object
            type: object
          gracefulShutDown:
            description: |-
              GracefulShutdownTimeout is the duration given to runnable to stop before the manager actually returns on stop.
              To disable graceful shutdown, set to time.Duration(0)
              To use graceful shutdown without timeout, set to a negative duration, e.G. time.Duration(-1)
              The graceful shutdown is skipped for safety reasons in case the leader election lease is lost.
            type: string
          health:
            description: Health contains the controller health configuration
            properties:
              healthProbeBindAddress:
                description: |-
                  HealthProbeBindAddress is the TCP address that the controller should bind to
                  for serving health probes
                type: string
              livenessEndpointName:
                description: LivenessEndpointName, defaults to "healthz"
                type: string
              readinessEndpointName:
                description: ReadinessEndpointName, defaults to "readyz"
                type: string
            type: object
          ingressPlugin:
            description: IngressPluginConfig contains the config for controlling ingress
              config
            properties:
              accessControl:
                description: AccessControlConfig contains the config for controlling
                  ingress snippet about Access control module
                properties:
                  redisConfigKey:
                    description: bk-ingress-nginx choose which redis key to connect
                      to, optional values 'prod', 'test', 'local'
                    type: string
                required:
                - redisConfigKey
                type: object
              paasAnalysis:
                description: PaaSAnalysisConfig contains the config for controlling
                  ingress snippet about PA(paas-analysis) module
                properties:
                  enabled:
                    description: Is PA enabled on the current cluster?
                    type: boolean
                required:
                - enabled
                type: object
              tenantGuard:
                description: |-
                  TenantGuardConfig contains the config for controlling ingress snippet about TenantGuard.
                  If TenantGuard is enabled, tenantGuardTemplate will be rendered in ingress.
                properties:
                  enabled:
                    description: Enabled true if TenantGuard is enabled
                    type: boolean
                required:
                - enabled
                type: object
            type: object
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          leaderElection:
            description: |-
              LeaderElection is the LeaderElection config to be used when configuring
              the manager.Manager leader election
            properties:
              leaderElect:
                description: |-
                  leaderElect enables a leader election client to gain leadership
                  before executing the main loop. Enable this when running replicated
                  components for high availability.
                type: boolean
              leaseDuration:
                description: |-
                  leaseDuration is the duration that non-leader candidates will wait
                  after observing a leadership renewal until attempting to acquire
                  leadership of a led but unrenewed leader slot. This is effectively the
                  maximum duration that a leader can be stopped before it is replaced
                  by another candidate. This is only applicable if leader election is
                  enabled.
                type: string
              renewDeadline:
                description: |-
                  renewDeadline is the interval between attempts by the acting master to
                  renew a leadership slot before it stops leading. This must be less
                  than or equal to the lease duration. This is only applicable if leader
                  election is enabled.
                type: string
              resourceLock:
                description: |-
                  resourceLock indicates the resource object type that will be used to lock
                  during leader election cycles.
                type: string
              resourceName:
                description: |-
                  resourceName indicates the name of resource object that will be used to lock
                  during leader election cycles.
                type: string
              resourceNamespace:
                description: |-
                  resourceName indicates the namespace of resource object that will be used to lock
                  during leader election cycles.
                type: string
              retryPeriod:
                description: |-
                  retryPeriod is the duration the clients should wait between attempting
                  acquisition and renewal of a leadership. This is only applicable if
                  leader election is enabled.
                type: string
            required:
            - leaderElect
            - leaseDuration
            - renewDeadline
            - resourceLock
            - resourceName
            - resourceNamespace
            - retryPeriod
            type: object
          maxProcesses:
            format: int32
            type: integer
          metadata:
            type: object
          metrics:
            description: Metrics contains thw controller metrics configuration
            properties:
              bindAddress:
                description: |-
                  BindAddress is the TCP address that the controller should bind to
                  for serving prometheus metrics.
                  It can be set to "0" to disable the metrics serving.
                type: string
            type: object
          platform:
            description: PlatformConfig contains the config for interacting with other
              service
            properties:
              customDomainIngressClassName:
                description: |-
                  CustomDomainIngressClassName works the same as IngressClassName, but only for ingress with custom domains.
                  Set customDomainIngressClassName if custom domain ingress needs to bound to a specific ingress controller,
                  otherwise it will be bound to the ingress controller specified by ingressClassName config
                type: string
              ingressClassName:
                description: if ingressClassName configured, kubernetes.io/ingress.class=$value
                  will be added to ingress's annotations
                type: string
              sentryDSN:
                description: sentry server dsn, all events waiting for report will
                  be dropped if unset
                type: string
            required:
            - customDomainIngressClassName
            - ingressClassName
            - sentryDSN
            type: object
          resLimits:
            description: ResLimitsConfig contains bkapp resource limits
            properties:
              maxReplicas:
                description: MaxReplicas is single instance max replica num
                format: int32
                type: integer
              procDefaultCPULimit:
                description: ProcDefaultCPULimit is process's default cpu quota
                type: string
              procDefaultMemLimit:
                description: ProcDefaultMemLimit is process's default memory quota
                type: string
            required:
            - maxReplicas
            - procDefaultCPULimit
            - procDefaultMemLimit
            type: object
          resRequests:
            description: |-
              NOTE: ResRequests 是 operator 为 BkApp 设置的默认 resource requests,
              仅当 BkApp 中 ResourceQuota 没有提供 requests 的情况下有效
            properties:
              procDefaultCPURequest:
                description: ProcDefaultCPURequest is process's default cpu request
                type: string
              procDefaultMemRequest:
                description: ProcDefaultMemRequest is process's default memory request
                type: string
            required:
            - procDefaultCPURequest
            - procDefaultMemRequest
            type: object
          syncPeriod:
            description: |-
              SyncPeriod determines the minimum frequency at which watched resources are
              reconciled. A lower period will correct entropy more quickly, but reduce
              responsiveness to change if there are many watched resources. Change this
              value only if you know what you are doing. Defaults to 10 hours if unset.
              there will a 10 percent jitter between the SyncPeriod of all controllers
              so that all controllers will not send list requests simultaneously.
            type: string
          webhook:
            description: Webhook contains the controllers webhook configuration
            properties:
              certDir:
                description: |-
                  CertDir is the directory that contains the server key and certificate.
                  if not set, webhook server would look up the server key and certificate in
                  {TempDir}/k8s-webhook-server/serving-certs. The server key and certificate
                  must be named tls.key and tls.crt, respectively.
                type: string
              host:
                description: |-
                  Host is the hostname that the webhook server binds to.
                  It is used to set webhook.Server.Host.
                type: string
              port:
                description: |-
                  Port is the port that the webhook server serves at.
                  It is used to set webhook.Server.Port.
                type: integer
            type: object
        required:
        - autoscaling
        - ingressPlugin
        - maxProcesses
        - platform
        - resLimits
        - resRequests
        type: object
    served: true
    storage: true
