description = "Ubuntu bionic base image with buildpacks for Apt, Go, Python and NodeJS"


[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/procfile:5.6.1"
  version = "5.6.1"


[[buildpacks]]
  uri = "../../buildpacks/bk-buildpack-python/cnb-buildpack"
  id = "bk-buildpack-python"
  version = "v213"


[[buildpacks]]
  uri = "../../buildpacks/bk-buildpack-nodejs/cnb-buildpack"
  id = "bk-buildpack-nodejs"
  version = "v163"


[[buildpacks]]
  uri = "../../buildpacks/bk-buildpack-go/cnb-buildpack"
  id = "bk-buildpack-go"
  version = "v205"


[[buildpacks]]
  uri = "../../buildpacks/bk-buildpack-apt/cnb-buildpack"
  id = "bk-buildpack-apt"
  version = "v2"


[lifecycle]
  uri = "https://bkpaas-runtimes-1252002024.cos.ap-shanghai.myqcloud.com/buildpacks/lifecycle-v0.17.6%2Bblueking.linux.x86-64.tgz"


[[order]]
  [[order.group]]
    id = "bk-buildpack-apt"
    version = "v2"


[[order]]
  [[order.group]]
    id = "bk-buildpack-python"
    version = "v213"


[[order]]
  [[order.group]]
    id = "bk-buildpack-nodejs"
    version = "v163"


[[order]]
  [[order.group]]
    id = "bk-buildpack-go"
    version = "v205"


[[order]]
  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.6.1"


[stack]
  id = "heroku-18"
  run-image = "mirrors.tencent.com/bkpaas/run-heroku-bionic:latest"
  build-image = "mirrors.tencent.com/bkpaas/build-heroku-bionic:latest"
